x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/drosophila_melanogaster_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/drosophila_melanogaster_100bp/dreme.html ../data/meme_data/in/random_dreme/drosophila_melanogaster_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/aedes_aegypti_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/aedes_aegypti_100bp/dreme.html ../data/meme_data/in/random_dreme/aedes_aegypti_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_albimanus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_albimanus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_albimanus_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_arabiensis_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_arabiensis_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_arabiensis_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_atroparvus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_atroparvus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_atroparvus_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_christyi_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_christyi_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_christyi_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_culicifacies_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_culicifacies_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_culicifacies_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_darlingi_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_darlingi_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_darlingi_upstream_dremeready_all_simpleMasked_random.fasta
x fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_dirus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_dirus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_dirus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_epiroticus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_epiroticus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_epiroticus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_farauti_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_farauti_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_farauti_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_funestus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_funestus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_funestus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_gambiae_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_gambiae_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_gambiae_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_maculatus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_maculatus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_maculatus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_melas_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_melas_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_melas_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_merus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_merus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_merus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_minimus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_minimus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_minimus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_quadriannulatus_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_quadriannulatus_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_quadriannulatus_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_sinensis_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_sinensis_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_sinensis_upstream_dremeready_all_simpleMasked_random.fasta
 fimo -verbosity 2 -oc ../data/meme_data/out/fimo_100bp/anopheles_stephensi_upstream -thresh 1.0 ../data/meme_data/out/dreme_100bp/sampled_all_hpc/anopheles_stephensi_100bp/dreme.html ../data/meme_data/in/random_dreme/anopheles_stephensi_upstream_dremeready_all_simpleMasked_random.fasta