from cogent.db.ensembl import HostAccount, Genome, Species

# anopheles_albimanus_core_1312_73_1

# example human antisense gene: 'ENST00000430895'

account = None
genome = Genome(Species='Human',Release='73',account=account)

#______________________________________________________
# TEST 1: absolute coords or relative to -/+ strand?
#______________________________________________________

# # A known antisense
# gene1 = genome.getGeneByStableId('ENSG00000234484') 		# Coordinate(Human,chro...,6,133073813-133075090,1)

# # A sense gense upstream from ^ but on - strand
# gene2 = genome.getGeneByStableId('ENSG00000146399') 		# Coordinate(Human,chro...,6,133073813-133075090,1)

# # A sense gene downstream from ^ but on + strand
# gene3 = genome.getGeneByStableId('ENSG00000271488')

# # Andy's predictions: if absolute coords are used, then gene2 < gene1 < gene3 == True
# print gene2.Location < gene1.Location < gene3.Location # Indeed, it seems absolute coords are used... YAY! 

Species.amendSpecies('anopheles albimanus','anopheles_albimanus')
account = HostAccount('localhost','vbuser','Savvas')
genome = Genome(Species='anopheles albimanus',Release='73',account=account)
gene = genome.getGeneByStableId('AALB004251')

#gene = genome.getGenesMatching('a')

#______________________________________________________
# TEST 2: Check if 2kb really is 2kb and not +/- 1 bp
#______________________________________________________

# Here's the printout of part of the sample_data dict loaded from pickle
# On sublime: Double click on "untruncated" then look at how many chars are selected
"""
{'truncated': '', 'untruncated': ''},
 {'truncated': 'TAGGCAATCGGTGTCCCATTTTTTGTTGCAGCAACAGCAGCAGCAGCAGCCTCAGCAGCCGCAACAGCAATCATTCCAGCAGCAGCAACAAGCACCCCCAGATCTGCAACAGAGCCTGCAGCATTCGCGGCATCAACTGCAGCTACAGCAAAACCAGTTGCAGCAACAGTTACAGCAGCAACAACAACAACATCGTACGCAGCATCAGCAATTGCAACAATTGCAGGCTCACCAGCAACATCATCCTGCATCACAGCAACAACCTCAGCAGACTCAGCTCATGGTACAAACGATGTCGGAGCCGGATTTGTTTGGTCCTAAGATAGCG',
  'untruncated': 'ATCGACTGTGCTGAAGTCGACGATTGCGTTCCTGAAGAGCCACAACGAGATCGCGGTACGGTCACGGGTACACGAGATCCAGACGGATTGGAAGCCATCGTTCCTGTCGAACGAAGAGTTTACGCATCTGATTCTGGAAGCACTGGACGGGTTCATCATCGTGTTCTCTTCCACCGGCAGAGTATTTTATGCGTCCGAAAGTATTACCTCCTTGTTGGGCCACTTACCGGTTAGTAGTGATTGGATGGTGTGACGTAGTATTTGCTAACGGTTTTGATGTTTTTTGCTGTTGTGATTCCAGAGTGATCTGCTCAACATGACCGTGTACGATATGGTGTACGAGGACGATCAGAATGATCTGTATCACATACTGCTTAACCCGACCACGATCGTGGATCCGCTTCAGACGGGCATTAGCCGAGAGAATCAGGTAACCTTTTCCTGTTACATCAAACGTGGAACGGTTGACTATCGGGCGGATGTGTCGTACGAGCATGTCCAGTTCACTGGGTACTTCCGTGAGTATACTAAGGCATGAAGAAGAAGGTCATGAAAGAGGTAAACATGGTGCTGAATGATGGCTCTTCGTAGGTAGTGACGTCGATACGGAATCTCTTATGACAACATCTCGGTTCAGCGGCTATACGAGCGATGCCGACTCTCGACTCGTGTTTGTAGGTACGGGTCGGCTGCAGACCCCGCAACTGATCCGCGAGATGTCGATCGTGGATAACACGAAAAGTGAGTTCACCTCCCGGCACAGCCTCGAATGGAAGTTCCTGTTTCTCGATCACCGGGCACCACCTATCATCGGCTACCTCCCGTTTGAAGTGCTGGGAACTTCCGGGTATGACTATTATCATTTTGACGATCTGGAAAAGGTGGTGGCTTGTCATGAAGCATGTAAGCTCTCACAGTATTACTACTACTGCCGTGCCCTCGTTCGCTACGGCGATCGCCTCTCCAAACGCATGGCCTGGCTTCACCGTACTCTTTCTCTTTTTCTTTACCTTCCCGTTTGTGTCTCTCTACTACTCTCGGCGTTGCTCGCCGTTTTGACGCTTATAGTGATGCAGAAAGGTGAGGGCACTTCGTGCTACTATCGATTCCTGACTAAAGGGCAGCAGTGGATCTGGCTGCAGACACGGTTCTACATCACCTACCATCAGTGGAACTCGAAGCCGGAGTTCGTGGTGTGTACGCATCGAGTGGTAAGCTATGCGGATGTGATGAAACAGATGCGCAACCAGACCGTGGCCGATGGCAAGTTCTCCGAGGATGCTGATAGCGTGAGTGTGCATGGTGTGGAGCGCAAATTTCAACAATCGTCCTCGCAGAGTCTGCTGGCAACGTCACCGTGGAGCTCGAAGAGTTCCCGAACGTCCCGGGTTGCACCGACACCGGGTGTGTCACCAACGGGGTTGTCTAACCGGGGACGCAATCGATACAACACCTACAACGGGCCTGGTTCCGACTCGGCCACGTCGATTTCCACCGAGTCACACACCAGTCGACAGTCCCTCGTTACGCAGCATTCGGTGAGTGTAAGCTACGGTGTGTAGGCATTAGACCAGTGTAGCTTGAACGATACGTTGGTTCTGTCTTTTTAGCGATCTCGTACGCGAACAAGCACATTCCCGCCAAAGGTTTCATCGCAGGGCAGTCAGCAGGATAGGCAATCGGTGTCCCATTTTTTGTTGCAGCAACAGCAGCAGCAGCAGCCTCAGCAGCCGCAACAGCAATCATTCCAGCAGCAGCAACAAGCACCCCCAGATCTGCAACAGAGCCTGCAGCATTCGCGGCATCAACTGCAGCTACAGCAAAACCAGTTGCAGCAACAGTTACAGCAGCAACAACAACAACATCGTACGCAGCATCAGCAATTGCAACAATTGCAGGCTCACCAGCAACATCATCCTGCATCACAGCAACAACCTCAGCAGACTCAGCTCATGGTACAAACGATGTCGGAGCCGGATTTGTTTGGTCCTAAGATAGCG'},
 {'truncated': '', 'untruncated': ''},
"""

#______________________________________________________
# TEST 2: Check if '1312' will work as Release=1312 for genome access
#______________________________________________________
from cogent.db.ensembl import HostAccount, Genome, Species
account = HostAccount('localhost','vbuser','Savvas')
Species.amendSpecies('Anopheles albimanus','anopheles albimanus')
genome = Genome(Species='Anopheles albimanus',Release=73,account=account)

