#########
# NOW   #
#########

# 14-05-27:
#   culex dreme_100bp has not technically finished yet
#       we are still watiting for it's dreme.txt to be generated in: /home/ab108/0VB/2kb/hpc/dreme/dreme_testing_e0.05_b2000/
#   for now, we have generated a "half-finished" version in: /home/ab108/0VB/2kb/hpc/dreme/dreme_testing_e0.05_b2000/rescue/dreme_culex.txt
#       the email with how we did this is found by searching for "xsltproc_lite" in outlook emails
#   

# 14-05-19:
#   a bit concerned about the error prone (manual) way I go about cleaning data generated by the upStream.py script
#   i'm assuming they are all over-written everytime upstream.py is ran?
#       let's test it
#           YES if you dont wipe out the legacy data then there can be legacy species that are not intended to be in the new run

# 14-05-10: 
#   made a backup of ../data/meme_data/in/* into ../data/meme_data/in/backup_05-10  <=  upDownStream.py may have generated flase data, due to the masking = 'simple' which was a flase arg called by meme_dataPrepper.py, check the WARN in there for more info

#------------------------------------------------------------------------------------------------------------#

#########
# TRASH #
#########

# 14-05-09:
#   made scripts/stamp_to_collapsed/collapse_biostar_v0502_cutCollapseStamp_v3.py   <-  is bad go with v2

echo Warning